
name: "windows Building C++ Applications CI workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  groovy-cpp-gradle-windows-2022:
    name: "Building C++ Applications Sample Groovy"
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Groovy"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type cpp-application --dsl groovy
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework junit-jupiter
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework spock
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run
          echo "==================Bundle the application=================================================================="              
          ./gradlew build           
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle        

  groovy-cpp-gradle-windows-2019:
    name: "Building C++ Applications Sample Groovy"
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Groovy"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type cpp-application --dsl groovy
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework junit-jupiter
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework spock
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run
          echo "==================Bundle the application=================================================================="              
          ./gradlew build           
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle 

  groovy-cpp-gradle-windows-2016:
    name: "Building C++ Applications Sample Groovy"
    runs-on: windows-2016
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Groovy"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type cpp-application --dsl groovy
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework junit-jupiter
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework spock
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run
          echo "==================Bundle the application=================================================================="              
          ./gradlew build           
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle 

  groovy-cpp-gradle-windows-latest:
    name: "Building C++ Applications Sample Groovy"
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Groovy"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type cpp-application --dsl groovy
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework junit-jupiter
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework spock
          # gradle init --project-name demo --type cpp-application --dsl groovy --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run
          echo "==================Bundle the application=================================================================="              
          ./gradlew build           
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle 